project:
  type: website
  output-dir: docs
  pre-render:
    - C:/Users/lobon/AppData/Local/miniconda3/python.exe xlsx_to_yml.py

# Metadata
description-meta: "Academic website of Lorenzo Bonasera"
author-meta: "Lorenzo Bonasera"

website:
  title: "Home"
  description: "Academic website of Lorenzo Bonasera"

  navbar:
    background: light
    left:
      - text: Notes
        href: tech-note.qmd

  page-navigation: true

  page-footer:
    left: "Lorenzo Bonasera &copy; <script>document.write(new Date().getFullYear())</script>"

  reader-mode: false
  search: false
  draft-mode: unlinked

  open-graph: true
  twitter-card: true

  site-url: "https://YOUR-GITHUB-USERNAME.github.io"

format:
  html:
    theme: cosmo
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript

execute:
  enabled: false
